# Generated by Django 2.2.4 on 2021-03-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_g_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secret_message',
        ),
    ]
